### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by shiqishidai1** [waylau/mongodb-file-server#6]
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:67) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:126) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117) ~[mongodb-driver-core-3.8.2.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[na:1.8.0_201]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85) ~[na:1.8.0_201]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_201]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_201]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_201]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_201]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_201]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_201]
	at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:64) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:62) ~[mongodb-driver-core-3.8.2.jar:na]
	... 3 common frames omitted

这个问题怎么处理，不是没用mongotemplate的bean吗，为什么之前还提示找不到这个bean,不是有两种方法可以实现这个吗，一个用这个bean，一个不用，你这个应该是不用的，为什么会提示找不到这个bean

**Comment by shiqishidai1** [comment]
![image](https://user-images.githubusercontent.com/48649984/55849902-de021580-5b84-11e9-8720-4a774c032289.png)
这是这个需要mongotemplate的bean的，我看过依赖了都导进去了，可是明明没有用到mongotemplate啊，为什么会需要这个bean，你的代码里也没有装配这个bean啊

**Comment by waylau** [comment]
没有用到这个bean，可能是框架内部用了。
看下，是版本的问题吗？还是应用编译的问题？
如果是jar下载失败，尝试使用下 独立部署Mongodb的模式。

**Comment by shiqishidai1** [comment]
是我没安装MongoDB,我看你书上没写要安装，后来安装了一下就好了，代码没问题，但是回头要用的时候还要单独打开这个项目运行吗？

**Comment by waylau** [comment]
可以装 MongoDB 也可以不装。不装就是内嵌模式的，重启数据就丢失了，主要是开发阶段用。如果是生产环境，还是钥装的。

**Comment by shiqishidai1** [comment]
不装就报错那个缺少mongotemplate的bean的错，装上启动以后就可以运行了，也不报错，感觉内嵌的不能用啊，内嵌的是不是要装插件？

**Comment by shiqishidai1** [comment]
内嵌的mongodb不会配置，尴尬网上也没什么完整的教程，只能配本地了

**Comment by shiqishidai1** [comment]
本地配置的配置文件怎么写，书上确实有，但是配置文件要写在哪里，写在哪个项目上，相应的还要写什么，总感觉你书上写的太简短了，说的不够详细

**Comment by shiqishidai1** [comment]
就是那个mongod.cfg的配置文件，有点没看懂

**Comment by shiqishidai1** [comment]
书里有些代码跟你在github里的代码不一样，就是到了某些章节，有些没改，有些就是不一样，做着很迷茫

**Comment by waylau** [comment]
github有做过升级，不一样是正常啊。~

内嵌的方式，服务器在国外可能包会下载失败。就用独立部署的方式吧

**Comment by shiqishidai1** [comment]
我下载了mongodb，用的本地的，但是配置不知道怎么写，没用过这个，配置写在哪里，写在文件服务器那个项目还是正在做的这个里面，不太懂，能浪费您10分钟写下流程么

**Comment by waylau** [comment]
不用写配置，安装了直接可以用
