### ISSUE TITLE
关于Linux系统运行

### ISSUE THREAD

**Issue by dovemy** [waylau/mongodb-file-server#8]
老师，我本地win10运行没有问题。但部署到远程的阿里轻量服务器CentOS7时，gradlew命令总是用不了，就用gradle命令运行起来，运行没有报错。有开放了防火墙，但是本地访问总是遭到拒绝连接，不知道和系统有没有关系。其他项目在阿里服务器上都能正常访问。

**Comment by dovemy** [comment]
Exception in thread "DisconnectableInputStream source reader" org.gradle.api.UncheckedIOException: java.io.IOException: Bad file descriptor
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:61)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
	at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:125)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Bad file descriptor
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:96)
	... 1 more

> Task :compileJava
Note: /home/pan/mongodb-file-server-master/src/main/java/com/waylau/spring/boot/server/config/SecurityConfig.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :processResources UP-TO-DATE
> Task :classes

> Task :bootRun

**Comment by waylau** [comment]
@DcXuhm  估计是阿里的防火墙的问题吧。你改为用 java -jar 运行方式试下

**Comment by dovemy** [comment]
问题已经解决：
在application.properties文件中将server.address=localhost修改为server.address=0.0.0.0。
原来的localhost会使项目在远程服务器上运行时仅对本地开放，而0.0.0.0则对外开放。
注意，端口需要提前在阿里防火墙设置处开放。
